language: python

python:
  - "3.8"

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9

install:
  - pip install pylint mys

script:
  - env CXX=g++-9 mys test
  - env CXX=g++-9 mys run
